name: Build, test & deploy

on: 
  push:
    branches:
      - main

env:
  PROJECT_VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: adopt
      - name: build with mvn clean (no tests)
        run: mvn clean package -DskipTests .
