name: Build, test & deploy

on: 
  push:
    branches:
      - main

env:
  PROJECT_VERSION: 1.0.0
  MVN_OPTS: -Dmaven.repo.local=~/dependencies/lib

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v4.1.2
        with:
          path: ~/dependencies/lib
          key: libraries
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: setup JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: adopt
      - name: build with mvn clean (no tests)
        run: mvn clean package -DskipTests ${{ env.MVN_OPTS }}
      - name: rename JAR file
        run: mv target/*.jar target/helloworld-${{ env.PROJECT_VERSION }}.jar
