name: Build, test & deploy

on: 
  push:
    branches:
      - main

env:
  PROJECT_VERSION: 1.0.0
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v4.1.2
        with:
          path: ${{ github.workspace }}/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: setup JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: adopt
      - name: build with mvn clean (no tests)
        run: mvn clean package -DskipTests 
        env:
          MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/.m2/repository"
      - name: rename JAR file
        run: mv target/*.jar target/helloworld-${{ env.PROJECT_VERSION }}.jar
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: setup JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: adopt
      - name: build with mvn clean (no tests)
        run: mvn test
